name: "checkout-in-ns3"
description: "Checkout this repository as ns-3 module"

# Requires wget!

runs:
  using: "composite"
  steps:
    - name: "Checkout this repository as ns-3 module"
      uses: actions/checkout@v4
      with:
        path: "src/lorawan"
    - name: "Download ns-3-dev working tree with Gitlab API"
      run: |
        tag=$(< src/lorawan/NS3-VERSION) && tag=${tag#release }
        wget -nv -O ns-3-dev.tar https://gitlab.com/api/v4/projects/nsnam%2Fns-3-dev/repository/archive.tar?sha=$tag
        tar -xf ns-3-dev.tar && cp -a ns-3-dev-$tag-*/. . && rm -R ns-3-dev.tar ns-3-dev-$tag*
      shell: bash
