# CI job to deploy the documentation on another repository
name: "Deploy the documentation"
run-name: "deploy-doc"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
    timeout-minutes: 120
    continue-on-error: true
    steps:
      # The following step is required in all jobs that use this repo's actions
      - name: "Retrieve actions from repository"
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github/actions
      - name: "Install dependencies and checkout repo in ns-3"
        uses: ./.github/actions/install-doc
      - name: "Build ns-3"
        env:
          BUILD_ID: per-commit-g++-debug
          COMPILER: g++
          MODE: debug
        uses: ./.github/actions/build
        with:
          save-ccache: "false"
          store-artifacts: "false"
      - name: "Build documentation"
        run: |
          ./ns3 docs doxygen-no-build
          make -C doc/models html
      - name: "Upload pages artifact"
        uses: actions/upload-pages-artifact@v3
        with:
          path: "doc/"

  deploy:
    # Add a dependency to the build job
    needs: build
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: "Deploy to GitHub Pages"
        id: deployment
        uses: actions/deploy-pages@v4
